.TH minigrep 1 "November 2024" "1.0" "Minigrep User Manual"
.SH Minigrep
Minigrep \- a program that searches files
.SH DESCRIPTION
The \fBMinigrep\fR program is a simple command-line tool.
Use as follows: minigrep <text being searched for> <file being searched in>
.SH AUTHOR
Written by Meownet.
.SH REPORTING BUGS
Report bugs to dexter@dexants.org.uk.
.SH COPYRIGHT
Copyright © 2024 meownet.  
This is free software; use freely in other programs if you want some searching functions in rust.
